# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'nipper_inspector.ui'
#
# Created by: PyQt5 UI code generator 5.12.3
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(594, 350)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton_LED1 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_LED1.setGeometry(QtCore.QRect(480, 120, 40, 40))
        font = QtGui.QFont()
        font.setFamily("Rounded Mgen+ 1c")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_LED1.setFont(font)
        self.pushButton_LED1.setObjectName("pushButton_LED1")
        self.pushButton_LED2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_LED2.setGeometry(QtCore.QRect(450, 80, 40, 40))
        font = QtGui.QFont()
        font.setFamily("Rounded Mgen+ 1c")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_LED2.setFont(font)
        self.pushButton_LED2.setObjectName("pushButton_LED2")
        self.pushButton_LED3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_LED3.setGeometry(QtCore.QRect(400, 50, 40, 40))
        font = QtGui.QFont()
        font.setFamily("Rounded Mgen+ 1c")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_LED3.setFont(font)
        self.pushButton_LED3.setObjectName("pushButton_LED3")
        self.pushButton_LED4 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_LED4.setGeometry(QtCore.QRect(350, 80, 40, 40))
        font = QtGui.QFont()
        font.setFamily("Rounded Mgen+ 1c")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_LED4.setFont(font)
        self.pushButton_LED4.setObjectName("pushButton_LED4")
        self.pushButton_FlowCapture = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_FlowCapture.setGeometry(QtCore.QRect(20, 240, 141, 41))
        font = QtGui.QFont()
        font.setFamily("Rounded Mgen+ 1c")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_FlowCapture.setFont(font)
        self.pushButton_FlowCapture.setObjectName("pushButton_FlowCapture")
        self.pushButton_LED5 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_LED5.setGeometry(QtCore.QRect(330, 120, 40, 40))
        font = QtGui.QFont()
        font.setFamily("Rounded Mgen+ 1c")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_LED5.setFont(font)
        self.pushButton_LED5.setObjectName("pushButton_LED5")
        self.pushButton_LED6 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_LED6.setGeometry(QtCore.QRect(360, 160, 40, 40))
        font = QtGui.QFont()
        font.setFamily("Rounded Mgen+ 1c")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_LED6.setFont(font)
        self.pushButton_LED6.setObjectName("pushButton_LED6")
        self.pushButton_LED7 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_LED7.setGeometry(QtCore.QRect(400, 180, 40, 40))
        font = QtGui.QFont()
        font.setFamily("Rounded Mgen+ 1c")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_LED7.setFont(font)
        self.pushButton_LED7.setObjectName("pushButton_LED7")
        self.pushButton_LED8 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_LED8.setGeometry(QtCore.QRect(450, 160, 40, 40))
        font = QtGui.QFont()
        font.setFamily("Rounded Mgen+ 1c")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_LED8.setFont(font)
        self.pushButton_LED8.setObjectName("pushButton_LED8")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 594, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.pushButton_LED1.clicked.connect(MainWindow.button_click_LED1)
        self.pushButton_LED2.clicked.connect(MainWindow.button_click_LED2)
        self.pushButton_LED4.clicked.connect(MainWindow.button_click_LED4)
        self.pushButton_FlowCapture.clicked.connect(MainWindow.button_click_FlowCapture)
        self.pushButton_LED3.clicked.connect(MainWindow.button_click_LED3)
        self.pushButton_LED5.clicked.connect(MainWindow.button_click_LED5)
        self.pushButton_LED6.clicked.connect(MainWindow.button_click_LED6)
        self.pushButton_LED7.clicked.connect(MainWindow.button_click_LED7)
        self.pushButton_LED8.clicked.connect(MainWindow.button_click_LED8)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton_LED1.setText(_translate("MainWindow", "1"))
        self.pushButton_LED2.setText(_translate("MainWindow", "2"))
        self.pushButton_LED3.setText(_translate("MainWindow", "3"))
        self.pushButton_LED4.setText(_translate("MainWindow", "4"))
        self.pushButton_FlowCapture.setText(_translate("MainWindow", "スキャン実行"))
        self.pushButton_LED5.setText(_translate("MainWindow", "5"))
        self.pushButton_LED6.setText(_translate("MainWindow", "6"))
        self.pushButton_LED7.setText(_translate("MainWindow", "7"))
        self.pushButton_LED8.setText(_translate("MainWindow", "8"))
